# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
### Get request with a header
GET http://localhost:8080/items
Accept: application/json

###

GET http://localhost:8080/owners
Accept: application/json

###


GET http://localhost:8080/transaction
Accept: application/json

###

### Send POST request with json body
POST http://localhost:8080/owners
Content-Type: application/json

{
  "first_name": "John",
  "last_name": "Super",
  "company_name": "IT company"
}

###

### Send POST request with json body
POST http://localhost:8080/owners
Content-Type: application/json

{
  "first_name": "John",
  "last_name": "Super",
  "company_name": "IT company"
}

###

### Send DELETE request with json body
DELETE http://localhost:8080/items/itemid/5

###

### Send POST request with json body
POST http://localhost:8080/items
Content-Type: application/json

{
  "title": "test item2111",
  "description": "test item description2111111111111111111111",
  "count": 20,
  "price": 2000,
  "date_stor": "2018-11-21T00:00:00"
}

###

### Send POST request with json body
POST http://localhost:8080/transaction
Content-Type: application/json

{
  "item": {"id": 3},
  "owner": {"id": 1 },
  "count": 4
}

###
