DROP TABLE ITEM;
DROP SEQUENCE item_sequence;

DROP TABLE OWNER;
DROP SEQUENCE owner_sequence;

DROP TABLE ACCOUNT;
DROP SEQUENCE account_sequence;


DROP TABLE TRANSACTIONS;
DROP SEQUENCE trans_sequence;

DROP TABLE CONTACT_DATA_TYPES;
DROP SEQUENCE cdt_sequence;


DROP TABLE CONTACT_DATA;
DROP SEQUENCE cd_sequence;


DROP TABLE ITEM_CAT_TYPES;
DROP SEQUENCE ict_sequence;


DROP TABLE ITEM_CATEGORIES;
DROP SEQUENCE ic_sequence;